### PR TITLE
feat(cache): Use Redis for caching #189

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@akonsowski 
@clarkjefcoat

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
I will fix the serialization issues with redis

**Comment by akonsowski** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
Depends on https://github.com/ozone-development/ozp-ansible/issues/24 to be finished

**Comment by clarkjefcoat** [comment]
Can you pull out the 60*60*24 expiry timeouts and use a config file variable instead?

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
