### PR TITLE
feat(listing): Ability to see if listing is bookmarked #159

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review:
@rkenyon1969 
@clarkjefcoat

### CODE REVIEW

**Comment by rkenyon1969** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Can you add a test where is_bookmarked is returned as False?

**Comment by mannyrivera2010** [comment]
I added more unit tests

**Comment by akonsowski** [comment]
:+1:  tests ran successfully on my backend

**Pull request merged**
