### PR TITLE
Profile listings

### PR DESCRIPTION
**Pull request by mannyrivera2010**

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
For Issue #132 

Please Review:
@clarkjefcoat 
@tonyalletag

**Comment by skhtet** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Manny and I have discussed changes needed to make the new API call correspond to 'owned' listings rather than 'viewable' listings.

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
