### PR TITLE
feat(listing): Add Listing DELETED to Activity Log #48

### PR DESCRIPTION
**Pull request by mannyrivera2010**
For Issue #48 
Please review:
@clarkjefcoat 
@rkenyon1969

### CODE REVIEW

**Comment by akonsowski** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
ShortListingSerializer will need in Listing.serializers.py will need 'is_deleted' value

**Comment by akonsowski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
👍

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
