### PR TITLE
chore(unit tests): Unit Tests for Settings, ozp_authorization, Profile API

### PR DESCRIPTION
**Pull request by mannyrivera2010**
* Refactoring of tests for ozp_authorization to make the test always run
* Added test for Settings file to check for the correct structure.
* Created Auth Mock Service
* Profile API Unit Test using Auth Mock Service

Please Review:
@clarkjefcoat 
@rkenyon1969

### CODE REVIEW

**Comment by rkenyon1969** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
Why did you comment out the organizations from the /api/self/profile tests?

**Comment by mannyrivera2010** [comment]
I commented the organization out because it was making the test fail when the authorization code replaced the values based on the response from the authorization service.  A system user shall not modified those values

**Comment by clarkjefcoat** [comment]
Yes, thanks.  Since we don't need organization in those tests go ahead and remove it rather than commenting it out.

**Comment by mannyrivera2010** [comment]
I removed the comments in those test

**Comment by mannyrivera2010** [comment]
The ````no auth refresh required```` acting weird in the unit test. 

````
{"time": "2016-04-21T19:49:03.907830+00:00", "message": "hitting url http://localhost:8000/demo-auth/users/Jones jones/info.json?issuerDN=None for user with dn Jones jones", "level": "DEBUG"}
{"time": "2016-04-21T19:49:03.908073+00:00", "message": "hitting url http://localhost:8000/demo-auth/users/Jones jones/groups/OZP/ for user with dn Jones jones for group info", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:03.926778+00:00", "message": "auth refreshed", "level": "DEBUG"}
{"time": "2016-04-21T19:49:03.928338+00:00", "message": "hitting url http://localhost:8000/demo-auth/users/Winston Smith wsmith/info.json?issuerDN=None for user with dn Winston Smith wsmith", "level": "DEBUG"}
{"time": "2016-04-21T19:49:03.928588+00:00", "message": "hitting url http://localhost:8000/demo-auth/users/Winston Smith wsmith/groups/OZP/ for user with dn Winston Smith wsmith for group info", "level": "DEBUG"}
{"time": "2016-04-21T19:49:03.951682+00:00", "message": "no auth refresh required. Expires in 2 seconds", "level": "DEBUG"}
..........{"time": "2016-04-21T19:49:30.995100+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.015898+00:00", "message": "auth refreshed", "level": "DEBUG"}
..{"time": "2016-04-21T19:49:31.039021+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.057596+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.077768+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.099047+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.118612+00:00", "message": "auth refreshed", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:31.132450+00:00", "message": "no auth refresh required. Expires in 86399 seconds", "level": "DEBUG"}
{"time": "2016-04-21T19:49:31.134548+00:00", "message": "no auth refresh required. Expires in 1 seconds", "level": "DEBUG"}
.{"time": "2016-04-21T19:49:39.405035+00:00", "message": "updating issuer dn for user jones", "level": "INFO"}
.{"time": "2016-04-21T19:49:39.410900+00:00", "message": "User Jones jones tried to login but is inactive", "level": "WARNING"}
.{"time": "2016-04-21T19:49:39.412491+00:00", "message": "creating new user for dn: Jones_jones", "level": "INFO"}
````

** no auth refresh required. Expires in 86399 seconds ** is not normal behavior

**Comment by mannyrivera2010** [comment]
I added tracing ability to authorization method.  
````
{"logger": "ozp-center.ozpcenter.auth.ozp_authorization", "level": "DEBUG", "message": "no auth refresh required. Expires in 86399 seconds", "method": "test_valid_cache", "user": "system", "time": "2016-04-22T16:20:43.291424+00:00"}
````
Log Message saying "86399 seconds" is normal behavior

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
