### PR TITLE
chore(documentation): API documentation

### PR DESCRIPTION
**Pull request by mannyrivera2010**

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
Please Review:
@tonyalletag 
@clarkjefcoat

**Comment by clarkjefcoat** [comment]
This documentation is great.  Thank you.

Can you add a comment to explain what the folder related changes in api/library/serializers.py do?

**Comment by mannyrivera2010** [comment]
I believe that we should not store '   ' (empty spaces) for the folder name as a valid folder name. 
The changes makes sure that empty spaces will be stored as null value instead of a ambiguous empty string

**Comment by clarkjefcoat** [comment]
:+1:

**Comment by tonyalletag** [comment]
:+1:

**Pull request merged**
