### PR TITLE
fix(Login):  Allow periods, double-quotes and backticks in usernames.

### PR DESCRIPTION
**Pull request by clarkjefcoat**
#152

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
@mannyrivera2010 
@akonsowski 
Please review.

**Comment by mannyrivera2010** [comment]
:+1:  
Only thing I would do is make Unit Test Changes in ozpcenter/tests/test_utils.py

**Comment by clarkjefcoat** [comment]
Tests added.  Thanks Manny.

**Comment by mannyrivera2010** [comment]
:+1:

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
