### PR TITLE
fix(library): Ability to bookmark apps that are enabled only #154

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Issue: #154 
Please Review:
@clarkjefcoat 
@rkenyon1969

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
Currently Working on Unit Test

**Comment by rkenyon1969** [comment]
:+1:

**Comment by rkenyon1969** [comment]
@mannyrivera2010 - Per our conversation, we should document the potential new bugs.

**Comment by mannyrivera2010** [comment]
@rkenyon1969 - I agree, we should use the issue page #154  to document it

**Comment by clarkjefcoat** [comment]
:+1:

**Pull request merged**
