### PR TITLE
feat(notification): Notifications Filtering (All, Pending, Expiring)

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Please Review
@rkenyon1969 
@akonsowski 

@wski

### CODE REVIEW

**Comment by akonsowski** [comment]
:+1:

**Comment by wski** [comment]
:+1: discussed with @mannyrivera2010 why the QuantifiedCode is failing, no big deal.

**Comment by rkenyon1969** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
QuantifiedCode gave some false positives errors. 
For "Avoid `None` as a redundant second argument to `dict.get()` Error" the lines are using MultiValueDict instead of Dict. so it behaves different.  
````python
listing_id = self.request.query_params.get('listing', None)
```
You need the None to avoid a MultiValueDictKeyError

**Pull request merged**
