### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by mannyrivera2010**
In reference to issue #195 

Please Review:
@rkenyon1969 
@clarkjefcoat 
@akonsowski

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
I need to fix new error with Redis:
````python
Exception while running run() in 'ozpcenter.scripts.sample_data_generator'
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django_extensions/management/email_notifications.py", line 63, in run_from_argv
    super(EmailNotificationCommand, self).run_from_argv(argv)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django_extensions/management/email_notifications.py", line 75, in execute
    super(EmailNotificationCommand, self).execute(*args, **options)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django_extensions/management/utils.py", line 71, in inner
    ret = func(self, *args, **kwargs)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django_extensions/management/commands/runscript.py", line 172, in handle
    run_script(mod, *script_args)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django_extensions/management/commands/runscript.py", line 80, in run_script
    mod.run(*script_args)
  File "/usr/local/ozp/backend/ozpcenter/scripts/sample_data_generator.py", line 59, in run
    books_ref.save()
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/db/models/base.py", line 710, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/db/models/base.py", line 747, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/dispatch/dispatcher.py", line 201, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/usr/local/ozp/backend/ozpcenter/models.py", line 312, in post_save_category
    cache.delete_pattern('metadata-*')
  File "/usr/local/ozp/python-env/lib/python3.4/site-packages/django/core/cache/__init__.py", line 131, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
AttributeError: 'DummyCache' object has no attribute 'delete_pattern'
````

**Comment by mannyrivera2010** [comment]
In the vagrant/staging/production machine, verify /usr/local/ozp/ozp.log file by running tail command
````tail -f /usr/local/ozp/ozp.log````
````
Errors: should be more complete.
````json
{
  "app_id": "ozp-backend",
  "app_version": "1.0.21",
  "backtrace": [
    {
      "file": "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py",
      "function": "dispatch",
      "line": 463,
      "text": "response = handler(request, *args, **kwargs)"
    },
    {
      "file": "/usr/local/ozp/backend/ozpcenter/api/notification/views.py",
      "function": "create",
      "line": 42,
      "text": "serializer.save()"
    },
    {
      "file": "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/serializers.py",
      "function": "save",
      "line": 175,
      "text": "self.instance = self.create(validated_data)"
    },
    {
      "file": "/usr/local/ozp/backend/ozpcenter/api/notification/serializers.py",
      "function": "create",
      "line": 196,
      "text": "validated_data['peer'])"
    },
    {
      "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
      "function": "create_notification",
      "line": 197,
      "text": "agency=agency)()"
    },
    {
      "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
      "function": "<lambda>",
      "line": 133,
      "text": "NotificationTypeEnum.SYSTEM: lambda: raise_(errors.PermissionDenied('Only app mall stewards can create system notifications')),"
    },
    {
      "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
      "function": "raise_",
      "line": 67,
      "text": "raise exception"
    }
  ],
  "environment": "dev",
  "hostname": "localhost.localdomain",
  "language": "Python 3.4.3",
  "levelname": "ERROR",
  "logger": "ozp-center.ozpcenter.errors",
  "message": "Only app mall stewards can create system notifications",
  "os": "Linux-2.6.32-573.el6.x86_64-x86_64-with-centos-6.7-Final",
  "process_id": 7725,
  "time": "2016-07-15T18:08:21.566370+00:00",
  "type": "PermissionDenied",
  "user": "jones"
}
````

**Comment by wski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
Completed.

Before:
````json
{
    "user": "jones",
    "logger": "django.request",
    "status_code": 500,
    "message": "Internal Server Error: /api/notification/",
    "time": "2016-07-15T16:37:19.124878+00:00",
    "level": "ERROR"
}
````

After:
````json
{
    "app_id": "ozp-backend",
    "app_version": "1.0.21",
    "backtrace": [
        {
            "file": "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/views.py",
            "function": "dispatch",
            "line": 463,
            "text": "response = handler(request, *args, **kwargs)"
        },
        {
            "file": "/usr/local/ozp/backend/ozpcenter/api/notification/views.py",
            "function": "create",
            "line": 42,
            "text": "serializer.save()"
        },
        {
            "file": "/usr/local/ozp/python-env/lib/python3.4/site-packages/rest_framework/serializers.py",
            "function": "save",
            "line": 175,
            "text": "self.instance = self.create(validated_data)"
        },
        {
            "file": "/usr/local/ozp/backend/ozpcenter/api/notification/serializers.py",
            "function": "create",
            "line": 196,
            "text": "validated_data['peer'])"
        },
        {
            "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
            "function": "create_notification",
            "line": 197,
            "text": "agency=agency)()"
        },
        {
            "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
            "function": "<lambda>",
            "line": 133,
            "text": "NotificationTypeEnum.SYSTEM: lambda: raise_(errors.PermissionDenied('Only app mall stewards can create system notifications')),"
        },
        {
            "file": "/usr/local/ozp/backend/ozpcenter/api/notification/model_access.py",
            "function": "raise_",
            "line": 67,
            "text": "raise exception"
        }
    ],
    "environment": "dev",
    "hostname": "localhost.localdomain",
    "language": "Python 3.4.3",
    "levelname": "ERROR",
    "logger": "ozp-center.ozpcenter.errors",
    "message": "Only app mall stewards can create system notifications",
    "os": "Linux-2.6.32-573.el6.x86_64-x86_64-with-centos-6.7-Final",
    "process_id": 7735,
    "time": "2016-07-15T18:15:04.938344+00:00",
    "type": "PermissionDenied",
    "user": "jones"
}
````

**Pull request merged**
