### PR TITLE
fix(ListingActivity): Admin tab fixes #141

### LINKED ISSUE #141: Quickview Modal - Admin tab record for approval is truncated
In the Quickview Modal in the Admin tab under "Listing Changes" after a listing a approved by an Org Steward there is a message that says " approved the listing for". But nothing is shown after the word "for".

The name of the Org that approved this listing should be shown after "for".

### PR DESCRIPTION
**Pull request by mannyrivera2010**
- Admin Tab Records for approval truncated
- Eliminated extra modified record for submitted action

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
This issue is related to #141 and #140 
Please review 
@rkenyon1969 
@clarkjefcoat

**Comment by rkenyon1969** [comment]
:+1:

**Comment by mannyrivera2010** [comment]
@clarkjefcoat 
When someone disable or enable a listing it is currently making two entries in the activities section in the admin tab. One entry for "Enabled" and one for "Modified"  or One entry for "Disabled" and "Modified". 
It was doing the same thing for Submitting a Listing before the fix. One entry  for "Submitted" and "Modified".
Do we want to only have one entry for an Enable and Disable Actions for a Listing?

**Comment by rkenyon1969** [comment]
As a new user, I would expect a modified entry only when the listing has
been modified. Enable, disable, submit are not modifications but state
changes. I would not include the extra entry.

**Comment by mannyrivera2010** [comment]
I agree with "Enable, disable, submit are not modifications but state changes.  I would not include the extra entry "

**Comment by clarkjefcoat** [comment]
We are all in agreement.  :+1:

**Comment by rkenyon1969** [comment]
:+1:

**Pull request merged**
