### PR TITLE
feat(plugins): Added plugin framework

### PR DESCRIPTION
**Pull request by mannyrivera2010**
This pull request for creating plug-able framework for authentication and authorization. due to restrictions some code cannot be pushed to github directly, therefor we need to be able to dynamically "plug in " functionality. 

Not completely done yet, missing unit test.

Please Review 
@arw180 
@clarkjefcoat 
@rkenyon1969

### CODE REVIEW

**Comment by clarkjefcoat** [comment]
I'd like to have a corresponding PR in ozp-ansible so that this could be deployed using the ozp-backend playbook.

**Comment by clarkjefcoat** [comment]
Next time you have a big PR please separate the PEP8 compliance changes into a different PR.

**Comment by akonsowski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Comment by clarkjefcoat** [comment]
The plugin directories were not included in the release.  I added a commit to fix that.
:+1:

**Pull request merged**
