### PR TITLE
chore(code-cleanup): Clean up code for maintainability

### PR DESCRIPTION
**Pull request by mannyrivera2010**
Clean up code for maintainability.
Used some suggestions from Quantified Code
https://www.quantifiedcode.com/app/project/13070c3c7b784cf88463f8cee86d5ea2 

Please Review:
@rkenyon1969 
@akonsowski

### CODE REVIEW

**Comment by mannyrivera2010** [comment]
Reference: https://docs.djangoproject.com/en/1.9/_modules/django/utils/datastructures/

**Comment by akonsowski** [comment]
:+1:

**Comment by rkenyon1969** [comment]
:+1:

**Comment by akonsowski** [comment]
:+1:

**Pull request merged**
